"""Initial migration

Revision ID: c2bfa0f29d21
Revises: 00b5fa03930f
Create Date: 2024-12-07 12:07:48.555548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bfa0f29d21'
down_revision = '00b5fa03930f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('o_auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('token_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('matric_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('school',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('school',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('matric_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    op.drop_table('o_auth_user')
    # ### end Alembic commands ###
